# Default state for all rules
default: true

# MD013 - Line length
MD013:
  line_length: 200
  code_blocks: false
  tables: false

# MD024 - Multiple headers with the same content
MD024:
  siblings_only: true
